spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory}
    username: ${DB_USERNAME:local-user}
    password: ${DB_PASSWORD:local-pass}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    web: debug